//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DadLibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadLibrary
    {
        public string ISBN10 { get; set; }
        public string ISBN13 { get; set; }
        public string Title { get; set; }
        public Nullable<int> Edition { get; set; }
        public string Author { get; set; }
        public string Genre { get; set; }
        public string Subject { get; set; }
        public Nullable<int> Copies { get; set; }
        public string Location { get; set; }
        public string KeyWords { get; set; }
        public string CallNum { get; set; }
        public Nullable<System.DateTime> LastRead { get; set; }
        public string LoanedOut { get; set; }
        public string LoanInfo { get; set; }
    }
}
